
import java.util.Arrays;
import java.lang.Math;
import java.util.Random;
import java.util.ArrayList;
import java.util.*;
import java.io.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luke
 */
public class cryptoJ1 extends javax.swing.JFrame {

    /**
     * Creates new form cryptoJ1
     */
    public cryptoJ1() {
        initComponents();
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("isbn check");

        jTextField2.setText("credit card check");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("isbn check");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("credit card check");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setText("prac3 bch encoding");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("prac3 bch decoding");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("BruteForce");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(32, 32, 32)
                .addComponent(jButton6)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int[] d = new int[10];
        String s;
        s = jTextField1.getText();

        for (int i = 0; i < 10; i++) {
            
            char  u = s.charAt(i);
            
            if (String.valueOf(u).equals("X")) {
                d[i] = 10;
            }
            else {
                d[i] = Integer.parseInt(String.valueOf(s.charAt(i)));
            }
        }
        
        System.out.println(Arrays.toString(d));
 
        int f = (d[0]+2*d[1]+3*d[2]+4*d[3]+5*d[4]+6*d[5]+7*d[6]+8*d[7]+9*d[8]+10*d[9]) % 11;
        
        if (f == 0)  {
            jTextArea1.setText("the isbn is valid in " + d[0]);
        }      
        else {
            jTextArea1.setText("the first character in the text field is " + d[0]);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int[] d = new int[10];
        String s;
        s = jTextField1.getText();
        
        for (int i = 0; i < 6; i++) {             
            d[i] = Integer.parseInt(String.valueOf(s.charAt(i)));
            
        }
        
        d[6] = (4*d[0]+10*d[1]+9*d[2]+2*d[3]+d[4]+7*d[5]) % 11; //  get syndromes
        d[7] = (7*d[0]+8*d[1]+7*d[2]+d[3]+9*d[4]+6*d[5]) % 11;  //  get syndromes
        d[8] = (9*d[0]+d[1]+7*d[2]+8*d[3]+7*d[4]+7*d[5]) % 11;  //  get syndromes
        d[9] = (d[0]+2*d[1]+9*d[2]+10*d[3]+4*d[4]+d[5]) % 11;   //  get syndromes
        
        if (d[6] == 10 || d[7] == 10 || d[8] == 10 || d[9] == 10) {  //check syndromes
            jTextArea1.setText("number unusable");
        }
        else {
                jTextArea1.setText(Arrays.toString(d));
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int[] d = new int[16];
        int[] d2 = new int[16];
        String s;
        int f = 0;
        int f2 = 0;
        
        s = jTextField1.getText();
        
        for (int i = 0; i < 16; i++){
            d[i] = Integer.parseInt(String.valueOf(s.charAt(i)));
        }
        
        for (int i = 0; i < 16; i = i + 2) {
            d[i] = d[i] * 2;
        }
        
        int total = 0;
        
        for (int i = 0; i < 16; i++){
            if (d[i] >= 10){
                d[i] = d[i] - 9;
            }
            total = total + d[i];
        }
        
        int s4;
        int n;
        
        s4 = (total % 10);
        
        if (s4 == 0){
            jTextArea1.setText("Credit Card Valid");
        }
        else {
            jTextArea1.setText("Credit Card Is Not Valid");
        }
    
            
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        int[] d = new int[16];
        String s;
        s = jTextField1.getText();
        
        for (int i = 0; i < 10; i++) {             
            d[i] = Integer.parseInt(String.valueOf(s.charAt(i)));
        }
        
        //System.out.println(d[0]);
        //System.out.println(d[9]);
        d[10] = ((d[0]+d[1]+d[2]+d[3]+d[4]+d[5]+d[6]+d[7]+d[8]+d[9]) % 11);                     //  get syndromes
        d[11] = ((d[0]+2*d[1]+3*d[2]+4*d[3]+5*d[4]+6*d[5]+7*d[6]+8*d[7]+9*d[8]+10*d[9]) % 11);  //  get syndromes
        d[12] = ((d[0]+4*d[1]+9*d[2]+5*d[3]+3*d[4]+3*d[5]+5*d[6]+9*d[7]+4*d[8]+d[9]) % 11);      //  get syndromes
        d[13] = ((d[0]+8*d[1]+5*d[2]+9*d[3]+4*d[4]+7*d[5]+2*d[6]+6*d[7]+3*d[8]+10*d[9]) % 11);  //  get syndromes
        
        int p = ((d[11]*d[11]) - (d[10]*d[12])) % 11;
        int q = (d[10]*d[13] - d[11]*d[12])% 11;
        int r = ((d[12]*d[12]) - d[11]*d[13]) % 11;
        
        if (p < 0)              // between 0 11
            p = p + 11;         // between 0 11
        if (q < 0)              // between 0 11
            q = q + 11;         // between 0 11
        if (r < 0)              // between 0 11
            r = r + 11;         // between 0 11
        
        
        System.out.println(Arrays.toString(d));
        System.out.println(d[10]);
        System.out.println(d[11]);
        System.out.println(d[12]);
        System.out.println(d[13]);
        System.out.println(p);
        System.out.println(q);
        System.out.println(r);
        System.out.println(Arrays.toString(d));
       
        
        if ((d[10] == 0) && (d[11] == 0) && (d[12] == 0) && (d[13] == 0)) {
            jTextField1.setText("no error");
        } 
        else if ((p == 0) && (q == 0) && (r == 0)) {
            jTextField1.setText("single error");
            int j = d[11] / d[10];                          // single error
            d[j-1] = d[10];
            System.out.println(Arrays.toString(d));
        }
        else if (p != 0 ||  q != 0 ||  r != 0) {
            jTextField1.setText("double error");        // double error
            
            int o = q*q-4*p*r;                      // quotient
            
            while (o < 0)
                o = o + 11;
            if (o > 11)
                o = o % 11;                         // mod 11 viable
            
            double root = (Math.sqrt(o));           // 
            
            //while ((root - Math.floor(root)) != 0)
            //    o = o + 11;
            //    root = (Math.sqrt(o));
            
           // double q2 = q;
            
            double n = -q + root;               // find positions
            double w = -q - root;               //find positions
            int n2 = (int) n;
            int w2 = (int) w;
            
            //System.out.println(n);
            //System.out.println(w);
            
            int b = ((n2 * d[10] - d[11]) * (n2 / w2));   // 
            d[n2] = b;                                    // magnitude     
            d[w2] = d[10] - b;                                // single error
            System.out.println(Arrays.toString(d));            // corrected
        }
        else {
            jTextField1.setText("more than two errors");

        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String[] d1;
        ArrayList<String> d = new ArrayList<String>();                      
        String bank = "abcdefghijklmnopqrstuvwxyz1234567890";
        for (int i = 0; i < 6; i++){
            Random rand = new Random();
            int x = rand.nextInt(36);     //36
            System.out.println(x);
            char ch = bank.charAt(x);
            String s = String.valueOf(ch); 
            d.add(s);
        }
        System.out.println(d);                      // TASK ATTEMPED ON PYTHON
        
        int[] tracker = new int[6];
        int[] trackers = {0, 0, 0, 0, 0, 0};
        
        for (int i = 0; i < 36; i++){
            for (int j = 0; i < 10; i++) {
                
            }
        }
        
        char arr[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
        int len = arr.length;
        crack(arr, len);


        
        
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cryptoJ1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cryptoJ1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cryptoJ1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cryptoJ1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cryptoJ1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
